export const POSTS_DATA_RECIEVED: string = 'POSTS/POSTS_DATA_RECIEVED';
export const POSTS_DATA_FAILURE: string = 'POSTS/POSTS_DATA_FAILURE';
export const POST_BY_ID_DATA_RECIEVED: string = 'POSTS/POST_BY_ID_DATA_RECIEVED';
export const ADD_COMMENT_REQUEST: string = 'POSTS/ADD_COMMENT_REQUEST';
